services:
  gib:
    build: .
    container_name: gib
    restart: unless-stopped
    # uncomment this if you have a physical env file in the same directory as the docker-compose.yml
    # env_file:
    #   - .env
    volumes:
      - /volume1/docker/gib/data:/data
